books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('book/<int:pk>/', views.BookView.as_view(), name='book'),
    path('author/<int:pk>/', views.AuthorView.as_view(), name='author'),
]

bookstore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('books/', include('books.urls')),
    path('admin/', admin.site.urls),
]

books/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

from datetime import datetime

CATEGORIES = (
    ('Novel', 'Novel'),
    ('Academic', 'Academic'),
    ('Action & Adventure', 'Action & Adventure'),
    ('Classic', 'Classic'),
    ('Mystery', 'Mystery'),
    ('Fantasy', 'Fantasy'),
    ('Fiction', 'Fiction'),
    ('Horror', 'Horror'),
    ('Romance', 'Romance'),
    ('Sci-Fi', 'Sci-Fi'),
    ('Thriller', 'Thriller'),
    ('Biography', 'Biography'),
    ('Literature', 'Literature'),
)


class Author(models.Model):
    author_name = models.CharField(max_length=250)
    biography = models.TextField(default='', null=True)

    def __str__(self) -> str:
        return self.author_name


class Publisher(models.Model):
    publisher_name = models.CharField(max_length=200)
    establish_date = models.DateTimeField('est')
    address = models.TextField()

    def __str__(self) -> str:
        return self.publisher_name


class Book(models.Model):
    book_name = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category = models.CharField(max_length=50, choices=CATEGORIES)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    price = models.FloatField(default=0)
    discount = models.FloatField(default=0)
    publication_date = models.DateTimeField('Publishing date')
    page_count = models.IntegerField(default=0)
    description = models.TextField()
    stock = models.IntegerField(
        default=0,
        validators=[MinValueValidator(0), ]
    )

    def __str__(self) -> str:
        return self.book_name


class Rating(models.Model):
    book = models.OneToOneField(Book, on_delete=models.CASCADE)
    rating = models.IntegerField(
        default=0,
        validators=[
            MinValueValidator(1),
            MaxValueValidator(5),
        ],
    )
    comment = models.TextField(
        default='', null=True,
    )
    time = models.DateTimeField(auto_now_add=True)

books/views.py
from django.shortcuts import render
from django.views import generic
from .models import *


class IndexView(generic.ListView):
    template_name = 'books/index.html'
    context_object_name = 'books'

    def get_queryset(self):
        return Book.objects.order_by('-publication_date')


class BookView(generic.DetailView):
    model = Book
    template_name = 'books/book.html'


class AuthorView(generic.DetailView):
    template_name = 'books/author.html'
    model = Author

books/templates/books/author.html
{% extends 'books/base.html' %}

{% load static %}
{% block content %}
<div class="container">
    <h1>{{ author.author_name }}</h1>
    <p>{{ author.biography }}</p>
</div>
{% endblock %}

books/templates/books/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BookFly | {{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'books/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'books/css/styles.css' %}" />
</head>
<body>
    <header class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'books:index' %}">BookFly</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'books:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">More options</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Coming Soon</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search functionality not active" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    {% block content %}

    {% endblock %}
</body>
</html>

books/templates/books/book.html
{% extends 'books/base.html' %}

{% load static %}
{% block content %}
<div class="container">
    <h1>{{ book.book_name }}</h1>
    <p><a href="{% url 'books:author' book.author_id %}">{{ book.author }}</a> - {{ book.publisher.publisher_name }}</p>
    <p>{{ book.category }}</p>
    <h4>{{ book.price }}</h4>
    <h6>{{ book.page_count }}</h6>
    <p>{{ book.description }}</p>
</div>
{% endblock %}

books/templates/books/index.html
{% extends 'books/base.html' %}

{% load static %}
{% block content %}
<div class="container">
    {% for book in books %}
    <a href="{% url 'books:book' book.pk %}">
        <h3>{{ book.book_name }}</h3>
        <a href="{% url 'books:author' book.author_id %}">{{ book.author }}</a>
    </a>
    <br>
    <hr>
    <br>
    {% endfor %}
</div>
{% endblock %}